### ISSUE TITLE
Houdini 15.5 import empty node.

### ISSUE THREAD

**Issue by emilsvfx** [heimlich1024/OD_CopyPasteExternal#11]
Copy node from Blender to Houdini 15.5 745 . It`s imports but in node the is no information empty node! But after some time it`s works but it`s cache old geometry.

https://cloud.githubusercontent.com/assets/22729351/25769827/97590036-322c-11e7-81b5-ab54d6134859.png

**Comment by heimlich1024** [comment]
it should work without problem.  However, in this particular case, it might be, that the source application still is writing the temporary file, and you are accessing it in houdini before its finished being written.  Please check that.
