### ISSUE TITLE
Export/import multiple objects

### ISSUE THREAD

**Issue by SYegor** [heimlich1024/OD_CopyPasteExternal#12]
Is it possible to exchange multiple objects?

**Comment by heimlich1024** [comment]
Currently no, its supposed to be an object at a time.  Depending on application, you can of course merge multiple objects together and transfer them as one.

**Comment by ThibH** [comment]
Should be doable though.
We'd have to decide wether we export multiple files separately for each object or everything in one file and have some kind of way to separate the different objects.
I tend to think exporting one file for each object could be cleaner but might take a bit longer if you have to open / close files multiple times.
Might be okay with 5 objects but longer and messier if you send a spaceship with 5,000 bolts.

**Comment by SYegor** [comment]
A large amount of object is of course an issue, but as well as a large amount of polygons. If you transfer a 1.5mil polygons mesh, it'll take a while. So user should know what he's doing in any case.

**Comment by ThibH** [comment]
Indeed, I tried with heavy meshes and it was not really usable because too slow.
But I guess the use people will have of this plugin is mostly to quickly transfer mesh from one software to another to use features that would not be available in their primary DCC. If you want to transfer a mesh to another software in the long run and keep it there you'd better export a proper file somewhere safe.

**Comment by heimlich1024** [comment]
yes.. its important to understand that this isn't supposed to be  a scene transfer, or a replacement for alembic in the long run.  They'll work side by side, but its more when you work on an individual mesh and know you can do certain aspects of operations quicker in another DCC.   As far as speed, I believe its less an issue with the ascii file, but more of an issue of python accessing structure of the DCC.  I am sure a C plugin will be much faster writing/reading the same file.

**Comment by heimlich1024** [comment]
In Lightwave & Modo, the way I implemented it, is via a simple command, and then just calling that command.  It would be very simple, to write a "frontend" that would give you access to layers and exporting layers that way.  I have an idea about it, but. I think its less critical to do right now, just to underline the purpose.

Regarding highres models, I also find (at least in our studio here) that we are less likely to do modling operations on million poly objects, which I guess why this has been less of an issue for us.  However, I'll be curious to do some performance comparisons.  I know specifically in Maya, there's a lot of performance to be gained, the initial implementation was very early, just trying to get it to work.  Its a lot faster in Lighwave/Houdini and Blender.

**Comment by ThibH** [comment]
For sure doing a Maya plugin in C/C++ would be faster to re-create the geometry.

**Comment by heimlich1024** [comment]
I know, just looking at my code, that there's a lot of room for optimization on all of it.  Currently, on my System here, 60k points takes 1 second, which i find "acceptable".

**Comment by heimlich1024** [comment]
I did some quick benchmarks... and as you can see, there's certainly room for a lot of improvement.

Benchmarks: (box with 200x200x200 segements (240k points))

LW Copy to External   		 3.2 seconds
LW Paste from External 		 4.8 seconds

Modo Copy To External		12.2 seconds
Mode Paste from External	 9.2 seconds

Houdini Copy To External	 7.4 seconds
Houdini Paste from External  7.0 seconds

3dsMax Copy To External		 4.2 seconds
3dsMax Paste from External	 6.0 seconds

**Comment by heimlich1024** [comment]
and as a comparison, just writing to a textfile 480k lines (240k points, 240k polys)
takes 0.5 seconds.  So its not the whole Ascii idea, writing to a text file thats doing the slowdown.

1.5 mil points, and polys (3 million lines), are 1.5 seconds.
