### ISSUE TITLE
C4D support

### ISSUE THREAD

**Issue by AndrezAguayo** [heimlich1024/OD_CopyPasteExternal#13]
Hello just wondering if anyone has started working on c4d integration yet? I am interested in trying to implement.

**Comment by heimlich1024** [comment]
There's a user that has.. He's close on the Paste portion and working on copy I believe.. it is not merged in yet as he's still working on it.

**Comment by heimlich1024** [comment]
you can see his branch currently under https://github.com/heimlich1024/OD_CopyPasteExternal/network

**Comment by heimlich1024** [comment]
added obj implementation for c4D until someone writes/finishes the c implementation
