### ISSUE TITLE
Xsi can't find temporary file

### ISSUE THREAD

**Issue by heimlich1024** [heimlich1024/OD_CopyPasteExternal#15]
XSI adds a temporary folder string during the session.. so the filepath:

filePath = os.path.dirname(os.path.normpath(tempfile.gettempdir())) + os.sep + "ODVertexData.txt"

needs to be changed to the actual temp folder (explorer %temp%)

**Comment by nunoalexconceicao** [comment]
If i use just tempfile.gettempdir() alone then yes I get the xsi temp dir, so thats why I'm doing  the os.path.dirname() and the result of that is the same path I got with explorer %temp%
