### ISSUE TITLE
3ds Max 2017 - Running scripts error

### ISSUE THREAD

**Issue by fredymartins** [heimlich1024/OD_CopyPasteExternal#18]
I get this message whenever I try and run the scripts in 3ds Max 2017:

![error](https://cloud.githubusercontent.com/assets/25802738/25832402/c669d8da-3440-11e7-8ec7-024b83365459.JPG)

**Comment by heimlich1024** [comment]
Could you please double check if in the .ms script, you give it the full path +  filename to the .py file ?  I just tested here on 2017, and it was working fine.  So please try to adjust the line to give it full path.

**Comment by fredymartins** [comment]
Yeah, but I keep getting the same error. 

![error1](https://cloud.githubusercontent.com/assets/25802738/25850444/ae4f79aa-3498-11e7-9b6f-af0f10c8a831.JPG)

I tried many different things. Here is one that I´m not pretty sure how to do, but might be helpful:

_"Do you have a python install on your computer outside of max? If so, 32bit?

I did find a solution, but I'm not exactly sure what was the problem.
I completely removed python from my machine, including site-packages and pythonpath. When I started max after that, everything works as expected.

The docs states that environment variables is loaded last, but in my sys.path, they showed up first. I suspect python in max loaded stuff from my local python install, which is 32bit, whereas max uses 64bit python. 
I will try reinstalling python, and keep testing with max until I find the error, if I can recreate it."_

I also tried this without success: http://area.autodesk.com/blogs/max-station/n240-solution-for-when-import-maxplus-gives-the-error-the-specified-module-could-not-be-found
