### ISSUE TITLE
maya_PasteFromExternal.py always create another mesh

### ISSUE THREAD

**Issue by xtvjxk123456** [heimlich1024/OD_CopyPasteExternal#19]
sorry for my english.
i found that when i paste mesh from external(like blender),maya always get another mesh named "tempobject{num}",it is Confused for me.
can fix it ?

**Comment by heimlich1024** [comment]
That is expected behavior.  In case you want to copy/paste multiple meshes, it would be bad if the already exiting one would be deleted/overwritten.  What do you think ?

**Comment by xtvjxk123456** [comment]
i agree with it

**Comment by xtvjxk123456** [comment]
i understand it now.
