### ISSUE TITLE
Blender intarface

### ISSUE THREAD

**Issue by Aenima108** [heimlich1024/OD_CopyPasteExternal#20]
Hello Oliver!
Thank you a lot for this amazing tool!

I install the tools through Preferences / Addons / Install from File. But object menu is empty, and i dont have Copy/Paste options. I have try on 2 different PC's with 2.78c Blender. Also I try to find this scripts in list of  Blender addons, but i didn't find it. Sorry, i dont know where is the Blender log file, but i add couple screenshots of intarface and system concole. Thanks again.

![object](https://cloud.githubusercontent.com/assets/28637425/25975992/6768700e-36ba-11e7-8028-5ac6bcfe446a.jpg)
![systemconsole](https://cloud.githubusercontent.com/assets/28637425/25975993/6768bdd4-36ba-11e7-813a-9e7a4f93ceed.jpg)

**Comment by heimlich1024** [comment]
when you install the plugin from file, did you make sure to check the "tickbox" to "activate" it ?

**Comment by Aenima108** [comment]
Im new in blender. As i wrote above, i can't find it in a list of Blender addons. Could you please send me a screenshots, where i should activate this tool after installation. Many thanks again.

**Comment by clintonman** [comment]
The names show as "Object: Copy To External" and "Object: Paste From External". You can filter the list by clicking on the Object category to make it easier to find them.
![blender_copypaste](https://cloud.githubusercontent.com/assets/5383136/26088696/760ddaae-39ad-11e7-9e10-81c172d71a44.jpg)

**Comment by Aenima108** [comment]
Thanks a lot Clintonman. I'm starting losing hope to help. Unfortunately it doesn't work for me, i have no idea why. In my list of blender addons this tools does not appear. May be i should install something yet before.

**Comment by heimlich1024** [comment]
Did you try adding each script one by one? Via install from file?

**Comment by Aenima108** [comment]
Yep. I already try all possible variants of installing.Both scripts placed in C:\.....\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons directory.

**Comment by clintonman** [comment]
Did you use the green "Clone or Download" button to download the scripts? If you look at the python file in a text editor it should start with something like:
bl_info = {
    "name": "Copy To External",
    "version": (1, 0),
    "author": "Oliver Hotz",
    "description": "Copies current object to clipboard for use in other applications / instances",
    "category": "Object"
}

Your error message sounds like it's not seeing these first few lines. If you copy and pasted the script text instead of downloading, that could be the problem.

**Comment by heimlich1024** [comment]
Did this resolve your issue?

**Comment by Aenima108** [comment]
Im sorry fo delay. Unfortunately i can't check this right now. After couple of days i will return to my PC, and let you know about results.
