### ISSUE TITLE
MAX: Copying from Max problems

### ISSUE THREAD

**Issue by hyerophant** [heimlich1024/OD_CopyPasteExternal#21]
Copying and pasting between LightWave and Modo worked fine.
Copying from LightWave and Modo, and pasting into MAX worked OK.

The problem occurs when copying from MAX.
If you work in MAX Japanese, you'll always get an error when you run the copy script (paste works fine).
You don't get that error in English ver, and it seems it is copying the geomery. However when pasting in other applications, all polygons are flipped and triangulated.
Flipping can be easily solved, but getting all polys triangulated is a big issue (specially when you need to keep cuad polys just as they are for ).

Is there any way to solve this?
(P.S: I turned my geometry to "Editable Poly" and "Editable Mesh", and get triangulated results in both cases.)

**Comment by heimlich1024** [comment]
I will be able to change the flipped part, however, I dont know 3dsmax well enough to do the hidden line to quad mesh.  Thats why I only did the very barebones implementation hoping for someone efficient in 3dsxmax to take that as a guide and run with it for a full implementation.

**Comment by hyerophant** [comment]
Thanks for the fast reply!
Hope that someone proficient in MAX gets the tweaks to get it solved.
For the time being, it is working fine in LW and Modo.
Thanks for such a great plugin, it is really helping a lot :)
