### ISSUE TITLE
3ds Max 2016 <-> Modo 10.2.2

### ISSUE THREAD

**Issue by jazznazz** [heimlich1024/OD_CopyPasteExternal#25]
Hey guys, great project, i hope it catches up!  :+1: 
Max -> Modo:
 - Flipped normals
 - the name of the object is not the same as in Max
Modo -> Max:
 - no smoothing groups after porting from Modo
 - no UVs
 - the object changes position to 0,0,0

**Comment by heimlich1024** [comment]
The max version is a very preliminary think I had done.  Unfortunately.  Its not something I can complete due to my lack of experience in the app and it needs to be done by someone more fluent in 3dsmax.
