### ISSUE TITLE
zbrush 4r8 

### ISSUE THREAD

**Issue by kouza** [heimlich1024/OD_CopyPasteExternal#27]
I can't see it in my zbrush 4r8 plugin...don't load at all...

**Comment by heimlich1024** [comment]
on windows or osx ?  did you copy the files into the correct folder ?

**Comment by heimlich1024** [comment]
![screenshot_3](https://user-images.githubusercontent.com/28104104/27893269-9d218698-61b9-11e7-95e2-f7930c5856e6.jpg)

**Comment by kouza** [comment]
Yes sure... 
![od](https://user-images.githubusercontent.com/26185464/27905832-884b09d2-6241-11e7-996d-e5c650cd0a45.JPG)

**Comment by heimlich1024** [comment]
could you try to load the script manually ?  Select the one within the odcopypaste folder/source/ZBRUSH_ODCopyPasteExternal.txt

**Comment by kouza** [comment]
I'll try , not working.

**Comment by kouza** [comment]
My apologies, i was looking for the icons "copy past" in the Zplugin menu ...
I did not realize what was at the end of the Tool menu, Work fine... thanks for everything
