### ISSUE TITLE
Moi3D - Error running paste script

### ISSUE THREAD

**Issue by gustojunk** [heimlich1024/OD_CopyPasteExternal#28]
hi there,  I tried the Modo-Moi3D workflow and I cant't get the script to work in Moi3D

When I run the "ODPasteFromExternal.js" in Moi from an alias I get error:

```
"ReferenceError: Can't find variable: ODPasteFromExternal

Line 1

1: >>  ODPasteFromExternal.js
```

I'm aslo confuse din what could I get to work in MOI3d, since AFAIK MOI does not support polygons inside its app, you can only make polygons on-export. So I will not have any polygons to copy in the Moi viewport, and I will not be able to paste any polygons either to it, correct?

Thanks,

Gustavo

**Comment by heimlich1024** [comment]
did you copy everything into the correct folders ?

**Comment by gustojunk** [comment]
I think so, it's all in 'C:\Program Files (x86)\MoI 3.0\commands' that's also where all the other .js scripts are.

**Comment by heimlich1024** [comment]
regarding the script.. did you map it as ODPasteFromExternal as command I assume  not with the .js right ?

Has to be something silly, as multiple people are running this fine..

**Comment by ThomasHelzle** [comment]
Every polygon is converted to a NURBS patch on import, so you can for instance use the Catmul Clark smoothing script from Max on the imported object. ( http://moi3d.com/forum/index.php?webtag=MOI&msg=6674) 
But you shouldn't import huge objects with tons of polys.
On export, everything is converted back to polygons...
Are you using MoI 3?
Works fine here :-)

**Comment by Talik6969** [comment]
Same issue. Doesn't work for me

UPDATE. This error happens if the command is made with a mistake in hotkeys editor. Works fine
