### ISSUE TITLE
Split Submodule

### ISSUE THREAD

**Issue by stilobique** [heimlich1024/OD_CopyPasteExternal#31]
Hello,
i don't know if make an issue are the best to discuss, but why not split all software with a submodule ? I'm work with Blender and Max and generate a depo for all software make more easily to keep the code clear and add more contribution. I think try to bring more feature for Max and Blender, but take all data don't help me for look the code.

**Comment by heimlich1024** [comment]
not sure exactly what you mean.  It should be pretty clear from the organization of the repo what is for which software.. and the docs folder explains the dataformat
