### ISSUE TITLE
Trojan:Wind32/Azden.A!cl

### ISSUE THREAD

**Issue by donovankeith** [heimlich1024/OD_CopyPasteExternal#34]
The objToVertData.exe file is being flagged as `Trojan:Win3/Azden.A!cl` by Windows' antivirus.
![virusalert](https://user-images.githubusercontent.com/4267389/30936507-f2dfd5ba-a388-11e7-809c-a9782fbcbbf9.jpg)

**Comment by heimlich1024** [comment]
hm.. that certainly shouldnt be happening, but might be, because it is unsigned ?.. not sure.
