### ISSUE TITLE
ZBrush version support

### ISSUE THREAD

**Issue by tiburbage** [heimlich1024/OD_CopyPasteExternal#38]
Based on the version check in line 14 of ZBrush/ODCopyPaste/source/ZBRUSH_ODCopyPasteExternal.txt, ZBrush 4R7 and greater are not supported yet. Since almost everyone is using R8, or at least R7, it would be great if they are supported. At least according to Pixologic, R8 is the last of the V4 releases, so there shouldn't be any more API changes until possibly V5 (which could be a long way away), so most users will likely be sitting on R8 for quite some time.

It would be a good if the full README.md, or a readme local to the ZB files, included information on supported versions/releases, and, assuming a successful install, where one would look for the entry points to the scripts (Zplugin menu I'm assuming, but not sure).

**Comment by heimlich1024** [comment]
Sorry, can't reproduce... this works in the latest 2019 just fine.
This doesn't show up on the plugin menu, You would find it under the tools menu.
