### ISSUE TITLE
Modo _  IntergrityCheckMissing ?

### ISSUE THREAD

**Issue by docAvalanche** [heimlich1024/OD_CopyPasteExternal#41]
This tool looks amazing, I am really hoping to get it working between Maya and Modo.
I am running the Steam Indie version of Modo 10 so I hope that isn't the issue, but I am getting this error in the script editor. Any help much appreciated! 

IntegrityCheckMissing: no valid hash for /SteamLibrary/steamapps/common/MODO indie 10/kits/OD_ModoCopyPasteExternal/lxserv/cmd_copyToExternal.py

python          Sun Jul 22 12:59:01 2018  Startup Skipping import of lxserv module "cmd_pasteFromExternal" due to an unhandled Python exception.
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\MODO indie 10\extra\Python\modules/lxserv.py", line 75, in <module>
    exec("import " + _m)
  File "<string>", line 1, in <module>
  File "<string>", line 2746, in load_module
  File "<string>", line 2888, in _load_verified_module
  File "<string>", line 2829, in _verify
  File "<string>", line 2333, in verify
IntegrityCheckMissing: no valid hash for /SteamLibrary/steamapps/common/MODO indie 10/kits/OD_ModoCopyPasteExternal/lxserv/cmd_pasteFromExternal.py

python          Sun Jul 22 12:59:01 2018  Info    I'm alive !!!
Scripts         Sun Jul 22 12:59:06 2018  Info    SDF_StripHaul.pl   (perl script)
Commands        Sun Jul 22 12:59:26 2018  Command paste failed
                Sun Jul 22 12:59:26 2018  Command   Command

**Comment by heimlich1024** [comment]
looks like its not compatible with Modo Indie, sorry
