### ISSUE TITLE
Not loading in Blender 2.83

### ISSUE THREAD

**Issue by Warner404** [heimlich1024/OD_CopyPasteExternal#49]
Hi Oliver

Looks like it's been mentioned - also not working in Blender 2.83. Plugins seem to load OK but looking at the add on prefs, there's a little waring icon and a "Upgrade to 2.8x required" message (see attached).

Would be great to have working (esp coming from LW's Modeler!!)
MacOS Catalina 10.15.5

<img width="712" alt="blenderError" src="https://user-images.githubusercontent.com/66419122/83750496-47809580-a65d-11ea-92d1-9740061895eb.png">

**Comment by heimlich1024** [comment]
should work in the 3.x now
