### ISSUE TITLE
Blender 2.9

### ISSUE THREAD

**Issue by olegzvg** [heimlich1024/OD_CopyPasteExternal#61]
Gives an error on "export to external", but model can be imported in houdini 19, although without UVs.
![image](https://user-images.githubusercontent.com/58860264/144194265-ea8bda45-3030-44f9-8228-ea8897402b09.png)

Import working correctly.

[system-info.txt](https://github.com/heimlich1024/OD_CopyPasteExternal/files/7631893/system-info.txt)

**Comment by heimlich1024** [comment]
fixed
