### ISSUE TITLE
Copying from Maya to Modo error

### ISSUE THREAD

**Issue by probiner** [heimlich1024/OD_CopyPasteExternal#8]
Copying from Modo to Maya works fine, but the other way around gives me an error in Modo:

Unhandled Python exception: exceptions.NameError; global name 'verts' is not defined from: 
C:\Users\Admin\AppData\Roaming\Luxology\Kits\OD_ModoCopyPasteExternal\xserv\cmd_pasteFromExternal.py: line 73
C:\Program Files\Luxology\modo\10.2v2\extra\Python\modules\lxu\command.py: line 157﻿

**Comment by heimlich1024** [comment]
Fixed.

**Comment by probiner** [comment]
| 
 | Pedro Alpiarça dos Santos 

         probiner.xyz 
 |

 

    On Monday, May 1, 2017 4:06 PM, Oliver Hotz <notifications@github.com> wrote:
 

 Fixed.—
