### ISSUE TITLE
Rhino support?

### ISSUE THREAD

**Issue by Ravneson** [heimlich1024/OD_CopyPasteExternal#9]
Could support for Rhino be considered for the roadmap?

**Comment by heimlich1024** [comment]
I'll add it to the list, but it'll need a person that uses Rhino to do the implementation.  I don't see any reason why it wouldn't be possible

**Comment by heimlich1024** [comment]
I added preliminary support.  For now, Just vertices and 3 & 4pt polygons.  Hopefully that'll give someone that is familiar with Rhino a jump start for a complete implementation.

**Comment by ThomasHelzle** [comment]
Thanks!

**Comment by Ravneson** [comment]
Brilliant, thanks!

**Comment by gustojunk** [comment]
I just tried the RHino scripts they don't work on my end here on Rhino V5 64-bit. Nothing gets either copied or pasted. Has anyone seen thins working well for them?

**Comment by heimlich1024** [comment]
are you trying to export nurbs, or polygons ?.. also remember, only 3&4pt polygons are supported.

**Comment by gustojunk** [comment]
yeah I meshed an object in Rhino. So it has only 3&$pt polygons since that's what its meshes does. 

I also tried to paste a cube created in Modo and also nothing happens. Even though I can paste it fine right back into Modo itself.

**Comment by heimlich1024** [comment]
i just tried it here and it works just fine.. (double check that maybe the object is extremely small in rhino)

Also are you maybe setting some specific environment variables for rhino, such as a non standard %temp% folder ?

**Comment by gustojunk** [comment]
thanks for trying. I played some more and I figured it out: Rhino was not executing the script from my default script folder, once I gave it the full path to where the scripts are located it sees them and works great. Thanks!
